services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-task_manager}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
